version: "3"

services:
  gradle:
    build:
      context: .
      args:
        - JDK_IMG_VERSION=${JDK_IMG_VERSION}
        - GRADLE_VERSION=${GRADLE_VERSION}
        - GRADLE_SHA=${GRADLE_SHA}
    volumes:
      - ..:/usr/share/app
      - ./volumes/gradle-cache:/root/.gradle/caches
