/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class common_VATACommands */

#ifndef _Included_common_VATACommands
#define _Included_common_VATACommands
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     common_VATACommands
 * Method:    reduce
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_common_VATACommands_reduce
  (JNIEnv *, jclass, jstring);

/*
 * Class:     common_VATACommands
 * Method:    checkInclusion
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_common_VATACommands_checkInclusion
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
